---

- name: Create NFS Storage Disk
  include: create-nfs.yml

- name: Manage Monitoring VM
  include: manage.yml name=project-{{ monitoring_vm }} type=e2-standard-2 group=monitor

- name: Manage Swarm Manager VMs
  include: manage.yml name=project-vm-manager1 type=e2-medium group=managers
- include: manage.yml name=project-vm-manager2 type=e2-medium group=managers
- include: manage.yml name=project-vm-manager3 type=e2-medium group=managers

- name: Manage worker VMs
  include: manage.yml name=project-vm-worker1 type=e2-medium group=workers
- include: manage.yml name=project-vm-worker2 type=e2-medium group=workers
- include: manage.yml name=project-vm-worker3 type=e2-medium group=workers

# - name: Delete NFS Storage Disk
  # include: delete-nfs.yml
