---

- name: Manage Monitoring VM
  include: manage.yml name=project-vm-monitoring type=e2-medium group=monitoring

- name: Manage Swarm Manager VMs
  include: manage.yml name=project-vm-manager1 type=e2-small group=manager
- include: manage.yml name=project-vm-manager2 type=e2-small group=manager
- include: manage.yml name=project-vm-manager3 type=e2-small group=manager

- name: Manage worker VMs
  include: manage.yml name=project-vm-worker1 type=e2-micro group=worker
- include: manage.yml name=project-vm-worker2 type=e2-micro group=worker
- include: manage.yml name=project-vm-worker3 type=e2-micro group=worker
