---

- 
  include: create.yml
  tags:
    - create-vms
  # We only want to import the inventory if the inventory isn't already imported by the -i option
  when: name not in hostvars.keys()

- 
  include: delete.yml
  tags:
    - delete-vms
  
-
  include: start.yml
  tags:
    - start-vms

- 
  include: stop.yml
  tags:
    - stop-vms
