---

- 
  include: create.yml
  tags:
    - provision

- 
  include: delete.yml
  tags:
    - delete-vms

-
  include: inventory.yml
  tags:
    - inventory
    - provision # When provisioning, we're always going to need the inventory
  
-
  include: start.yml
  tags:
    - start-vms

- 
  include: stop.yml
  tags:
    - stop-vms
