--- 

# GCP Authentication Configuration
gcp_project: marine-cycle-273002
gcp_auth_kind: serviceaccount
gcp_service_account_file: ./marine-cycle.json

# App configuration
region: europe-west1
zone: europe-west1-b

env_vars:
    # Misago: gunicorn
    MISAGO_PORT: 8000
    DJANGO_WSGI_MODULE: devproject.wsgi
    DJANGO_SETTINGS_MODULE: devproject.settings

    # PostgreSQL
    POSTGRES_DB: misago
    POSTGRES_USER: misago
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432

    # REDIS
    REDIS_MASTER_HOST: redis-master
    REDIS_PORT: 6379
    REDIS_PASSWORD: str0ng_passw0rd
    ADMIN_USERNAME: admin
    ADMIN_PASSWORD: password
    REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 5000
    REDIS_SENTINEL_FAILOVER_TIMEOUT: 10000
    REDIS_SENTINEL_QUORUM: 1

    # REDIS SENTINEL
    SENTINEL_PORT: 26379

    # Monitoring
    MONITOR_IP: '{{ hostvars[groups["monitor"][0]]["internal_ip"] }}'
