version: "3.8"

networks:
    # network for App <-> Redis transactions
    misago-redis-in:
        driver: overlay
        internal: true
    # network for App <-> DB transactions
    misago-postgres-in:
        driver: overlay
        internal: true
    # network for App <-> Nginx transactions
    misago-nginx:
        driver: overlay
        internal: true
    # network for * <-> Celery transactions
    misago-celery:
        driver: overlay
        internal: true
    # this network faces the outside world
    misago-out:
        driver: overlay
        internal: false

services:
    postgres:
        image: postgres
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - misago-postgres-in
        volumes:
            - /nfs/misago/pg:/var/lib/postgresql/data/:z
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    redis:
        image: redis
        command: redis-server --requirepass alsosecret
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - misago-redis-in
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    misago:
        image: vascoalramos/misago-app
        ports:
            - ${MISAGO_PORT}:80
        env_file: .env
        networks:
            - misago-redis-in
            - misago-postgres-in
            - misago-celery
            - misago-nginx
        depends_on:
            - postgres
            - redis
        volumes:
            - /nfs/misago/static_files/:/static:rw
            - /nfs/misago/media_files/:/media:rw
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure

    celery:
        image: vascoalramos/misago-celery
        command: /bin/bash -c "cd /opt/misago && celery -A devproject worker --loglevel=info"
        env_file: .env
        networks:
            - misago-redis-in
            - misago-postgres-in
            - misago-celery
        depends_on:
            - misago
            - postgres
            - redis
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    web:
        image: vascoalramos/misago-web
        ports:
            - 80:80
        environment:
            - APP_HOST=misago
            - APP_PORT_NUMBER=80
        networks:
            - misago-nginx
            - misago-out
        depends_on:
            - misago
        volumes:
            - /nfs/misago/static_files/:/static:r
            - /nfs/misago/media_files/:/media:r
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
