version: "3.8"

networks:
    # network for App <-> Redis transactions
    misago-redis-in:
        internal: true
    # network for App <-> DB transactions
    misago-postgres-in:
        internal: true
    # network for App <-> Nginx transactions
    misago-nginx:
        internal: true
    # network for * <-> Celery transactions
    misago-celery:
        internal: true
    # this network faces the outside world
    misago-out:
        internal: false
    # this network is used to connect with elasticsearch instance
    monitor:
        internal: false

services:
    web:
        build: web
        ports:
            - 80:80
        environment:
            - APP_HOST=misago
            - APP_PORT_NUMBER=80
        networks:
            - misago-nginx
            - misago-out
        depends_on:
            - misago

    misago:
        build:
            context: ../..
            dockerfile: deployment/docker/misago/Dockerfile
        ports:
            - ${MISAGO_PORT}:80
        env_file: .env
        networks:
            - misago-redis-in
            - misago-postgres-in
            - misago-celery
            - misago-nginx
        depends_on:
            - postgres
            - redis

    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - misago-postgres-in
            - monitor
        volumes:
            - database-data:/var/lib/postgresql/data/

    metricbeat:
        image: docker.elastic.co/beats/metricbeat:7.1.0
        volumes:
            - ./metricbeat/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
        networks:
            - monitor
        depends_on:
            - postgres

    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - misago-redis-in
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    celery:
        build:
            context: ../..
            dockerfile: ./deployment/docker/celery/Dockerfile
        command: /bin/bash -c "cd /opt/misago && celery -A devproject worker --loglevel=info"
        env_file: .env
        networks:
            - misago-redis-in
            - misago-postgres-in
            - misago-celery
        depends_on:
            - misago
            - postgres
            - redis

volumes:
    database-data:
