version: "3.8"

services:
    web:
        build:
            context: ../..
            dockerfile: ./deployment/docker/misago/Dockerfile
        ports:
            - ${MISAGO_PORT}:80
        env_file: .env
        depends_on:
            - postgres
            - redis

    postgres:
        image: postgres
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - database-data:/var/lib/postgresql/data/

    redis:
        image: redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    celery:
        build:
            context: ../..
            dockerfile: ./deployment/docker/misago/Dockerfile
        command: /bin/bash -c "cd /opt/misago && celery -A devproject worker --loglevel=info"
        env_file: .env
        depends_on:
            - postgres
            - redis

volumes:
    database-data:
