metricbeat.config:
    modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

metricbeat.modules:
    - module: postgresql
      hosts: ["postgres://postgres:5432?sslmode=disable"]
      metricsets:
          - database
          - bgwriter
          - activity
          - statement
      period: 10s
      enabled: true
      username: misago
      password: secret

setup.template.settings:
    index.number_of_shards: 1
    index.codec: best_compression

setup.kibana:
    host: "${MONITOR_IP}:${KIBANA_PORT}"

output.elasticsearch:
    hosts: ["${MONITOR_IP}:${ELASTIC_PORT}"]
