plugin: gcp_compute
auth_kind: serviceaccount
service_account_file: ./marine-cycle.json
projects:
  - marine-cycle-273002
keyed_groups:
  - key: labels['type']
    separator: ""
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  internal_ip: networkInterfaces[0].networkIP
