---

- name: Scale containers
  hosts: managers
  run_once: true
  become: yes
  tasks:
      - name: Scale web service containers
        shell: "docker service scale misago_web={{ lookup('vars', 'web') | int }}"
        when: web is defined
      
      - name: Scale celery service containers
        shell: "docker service scale misago_celery={{ lookup('vars', 'celery') | int }}"
        when: celery is defined
      
      - name: Scale misago service containers
        shell: "docker service scale misago_misago={{ lookup('vars', 'misago') | int }}"
        when: misago is defined
